name: Build Demo Reports
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: '3.11' }
      - run: python -m pip install --upgrade pip
      - run: pip install -r 01_robustness_svd_cholesky/python/requirements.txt
      - run: pip install -r 02_uncertainty_conformal_bootstrap/python/requirements.txt
      - run: pip install -r 03_offset_model_weakness/python/requirements.txt || true
      - run: python 01_robustness_svd_cholesky/python/run_robustness.py
      - run: python 02_uncertainty_conformal_bootstrap/python/run_uncertainty.py
      - run: python 03_offset_model_weakness/python/run_offset.py || true
      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: reports
  deploy:
    needs: build
    permissions: { pages: write, id-token: write }
    runs-on: ubuntu-latest
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
